"""empty message

Revision ID: 02c261e839f5
Revises: f34a3b9ecaa4
Create Date: 2023-02-12 03:30:12.758114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c261e839f5'
down_revision = 'f34a3b9ecaa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('draft_data', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'draft_data')
    # ### end Alembic commands ###
