"""empty message

Revision ID: 22635cc03a3c
Revises: a47829eca42c
Create Date: 2023-02-05 13:57:43.863527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22635cc03a3c'
down_revision = 'a47829eca42c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('event_creator_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'event_creator_id')
    # ### end Alembic commands ###
