"""empty message

Revision ID: 5ebb0a9fe5f9
Revises: ee97e6571bc0
Create Date: 2023-02-08 19:19:34.600063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ebb0a9fe5f9'
down_revision = 'ee97e6571bc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'profile_pic_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'profile_pic_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
