"""empty message

Revision ID: 637517933a50
Revises: 5ebb0a9fe5f9
Create Date: 2023-02-09 14:24:26.358512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '637517933a50'
down_revision = '5ebb0a9fe5f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('created_by_id', sa.Integer(), nullable=False))
    op.drop_column('event', 'created_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('event', 'created_by_id')
    # ### end Alembic commands ###
