"""empty message

Revision ID: 9237868dbad0
Revises: 
Create Date: 2024-01-28 20:10:10.121015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9237868dbad0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('date_time_start', sa.DateTime(), nullable=False),
    sa.Column('date_time_stop', sa.DateTime(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('video_conf_link', sa.String(), nullable=True),
    sa.Column('meeting_key', sa.String(), nullable=True),
    sa.Column('online_in_person', sa.String(), nullable=False),
    sa.Column('location_address', sa.String(), nullable=True),
    sa.Column('location_lat', sa.String(), nullable=True),
    sa.Column('location_lng', sa.String(), nullable=True),
    sa.Column('organizer_first_name', sa.String(), nullable=True),
    sa.Column('organizer_last_name', sa.String(), nullable=True),
    sa.Column('organizer_pronouns', sa.String(), nullable=True),
    sa.Column('organizer_email', sa.String(), nullable=True),
    sa.Column('target_audience', sa.String(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('date_time_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('pronouns', sa.String(), nullable=True),
    sa.Column('cohort', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=False),
    sa.Column('location_lat', sa.String(), nullable=True),
    sa.Column('location_lng', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('profile_pic_file', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('linkedin', sa.String(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('years_experience', sa.String(), nullable=True),
    sa.Column('include_name_salary', sa.String(), nullable=False),
    sa.Column('user_first_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_user',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('event_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_user')
    op.drop_table('user')
    op.drop_table('event')
    # ### end Alembic commands ###
