"""empty message

Revision ID: cb4e02b0b71a
Revises: 8808f72c3b5b
Create Date: 2023-02-12 19:52:04.828163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb4e02b0b71a'
down_revision = '8808f72c3b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'draft_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('draft_data', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
