"""Add nullable info to Event attributes

Revision ID: d89f7f14dda0
Revises: dc18b061de14
Create Date: 2023-01-29 22:20:56.900171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd89f7f14dda0'
down_revision = 'dc18b061de14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('event', 'location_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('event', 'location_lat',
               existing_type=sa.NUMERIC(precision=8, scale=6),
               nullable=True)
    op.alter_column('event', 'location_lng',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               nullable=True)
    op.alter_column('event', 'organizer_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('event', 'organizer_first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('event', 'organizer_last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('event', 'target_audience',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('event', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'location_lat',
               existing_type=sa.NUMERIC(precision=8, scale=6),
               nullable=True)
    op.alter_column('user', 'location_lng',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'location_lng',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               nullable=False)
    op.alter_column('user', 'location_lat',
               existing_type=sa.NUMERIC(precision=8, scale=6),
               nullable=False)
    op.alter_column('event', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('event', 'target_audience',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('event', 'organizer_last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('event', 'organizer_first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('event', 'organizer_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('event', 'location_lng',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               nullable=False)
    op.alter_column('event', 'location_lat',
               existing_type=sa.NUMERIC(precision=8, scale=6),
               nullable=False)
    op.alter_column('event', 'location_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('event', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
