"""empty message

Revision ID: f34a3b9ecaa4
Revises: 637517933a50
Create Date: 2023-02-10 18:30:49.821250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f34a3b9ecaa4'
down_revision = '637517933a50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('date_time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'date_time_created')
    # ### end Alembic commands ###
